Added delimiter option to import and export options
agentejo/Lokalize pull request #8
Opened 2020-06-17 00:32 UTC by davidsims9t

This exposes an config option to specify a delimiter in import/export. I think this is a fairly straight-forward change. My team requires that we import/export using comma delimited values.

2020-06-17 00:35 UTC, aheinze requested changes

2020-06-17 00:35 UTC, aheinze commented on README.md
> +    delimiter: false,
I would add `";"` here to make clear that you can change it to a comma

2020-06-18 17:12 UTC, davidsims9t commented
@aheinze can you please review this again

2020-06-18 20:48 UTC, merged

2020-06-18 20:48 UTC, aheinze commented
Thanks!